- main.go
> Enforce a repo or an org flag

- exporter/exporter.go
> Renamed valid_response to up

- CHANGELOG.md
- changelog/insecure-tls.md
- docs/content/getting-started.md
- pkg/action/server.go
- pkg/command/command.go
- pkg/config/config.go
My company GHE instance uses a self-signed cert from our private CA..
> Allow insecure TLS via CLI flag

- CHANGELOG.md
- changelog/unreleased/fix-wildcard.md
- pkg/exporter/repo.go
Fixes https://github.com/promhippie/github_exporter/issues/75
> fix: resolve fetching of private repos

- changelog/2.0.1_2023-03-23/privatekey-parse.md
- pkg/action/server.go
Fixes https://github.com/promhippie/github_exporter/issues/185
> fix: better handling private key loading

- changelog/unreleased/fix-nil-pointer.md
- pkg/exporter/admin.go
- pkg/exporter/billing.go
- pkg/exporter/helper.go
- pkg/exporter/org.go
- pkg/exporter/runner.go
- pkg/exporter/workflow.go
Fixes https://github.com/promhippie/github_exporter/issues/216
> fix: resolve nil pointer errors

- changelog/unreleased/ghe-app-support.md
- changelog/unreleased/workflow-status.md
- pkg/action/server.go
Fixes https://github.com/promhippie/github_exporter/issues/228
> Add support for apps on GitHub Enterprise

- pkg/action/server.go
Fixes https://github.com/promhippie/github_exporter/issues/228
> feat: append api suffix to ghe app url

- pkg/exporter/org.go
This is useful to track when we need to order more seats for GitHub.
Specially as you can't instantly increase seats on an enterprise account.
> feat: Add seats metrics to org exporter

- .gitignore
- changelog/3.0.1_2023-10-27/fix-database.md
- pkg/store/generic.go
Fixes https://github.com/promhippie/github_exporter/issues/270
> fix: correctly store and retrieve db records

- changelog/unreleased/sqlite-path.md
- pkg/store/sqlite.go
Fixes https://github.com/promhippie/github_exporter/issues/278
> fix: make sure the sqlite dir exists

- changelog/unreleased/workflow-timestamps.md
- pkg/exporter/workflow.go
Fixes https://github.com/promhippie/github_exporter/issues/281
> feat: add created, updated and started timestamp metrics for workflows

- changelog/unreleased/drop-out-of-order-events.md
- pkg/store/generic.go
Fixes: https://github.com/promhippie/github_exporter/issues/296
> Drop out of order workflow webhook events

- changelog/unreleased/actor_login.md
- docs/partials/envvars.md
- pkg/action/server.go
- pkg/config/config.go
- pkg/store/chai.go
- pkg/store/generic.go
- pkg/store/mysql.go
- pkg/store/postgres.go
- pkg/store/sqlite.go
- pkg/store/types.go
Export `actor.login` label for workflow collector
Not sure about the db tho, adding this feat. I used `chai` and did hit `column not found` few times until nuked everything that's in `cmd/github_exporter/storage/` to overcome this...
> Add actor.login label to workflow collector

- CONTRIBUTING.md
- docs/content/application.md
- docs/content/building.md
- docs/content/usage.md
- docs/partials/metrics.md
- hack/compose/README.md
- pkg/exporter/workflow.go
While setting up the project locally for development, I noticed a few typos here and there.
> chore: Fix a few typos

- pkg/action/server.go
Also makes the log output nicer
> fix: return after throwing internal status error to avoid trying to write response twice

- pkg/command/command.go
> fix: add error to db ping failure log

- pkg/config/config.go
- pkg/store/generic_workflow_job.go
- pkg/store/types.go
- **fix: update conclusion and completed_at timestamp**
- **fix: include identifier in labels to ensure unique series**
> A couple of bugfixes for collection in workflow_job

- changelog/4.0.1_2024-10-31/fix-db-ping.md
- changelog/4.0.1_2024-10-31/fix-include-identifier.md
- changelog/4.0.1_2024-10-31/fix-pg-schema.md
- changelog/4.0.1_2024-10-31/fix-runner-id.md
- changelog/4.0.1_2024-10-31/fix-update_completed_at.md
Updated changelog for new release.
> chore: update changelog for 4.0.1

- docs/content/webhook.md
I wasn't able to get the Workflow Jobs working until I enabled the `Workflows Jobs` in the webhook. Suggest adding this to the docs.
> Update Docs for Workflows Jobs collector (webhook info)

- pkg/command/command.go
- pkg/config/config.go
- pkg/exporter/workflow_job.go
- pkg/exporter/workflow_job_test.go
- pkg/exporter/workflow_run.go
- pkg/store/chai.go
- pkg/store/generic_workflow_job.go
- pkg/store/generic_workflow_run.go
- pkg/store/mysql.go
- pkg/store/postgres.go
- pkg/store/sqlite.go
- pkg/store/store.go
This allows longer retention in the database if you want to expose the underlying database directly for analysis.
> feat: allow specifying purge window separately from the window

- changelog/unreleased/job-updates.md
- hack/generate-envvars-docs.go
- pkg/store/generic_workflow_job.go
Fixes https://github.com/promhippie/github_exporter/issues/485
> fix: always update runner labels for workflow jobs

- Taskfile.yml
> fix: use correct build tags within build task for docker
